apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: oauth_start
  namespace: demo
  labels:
    applicationName: oauth_start
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service oauth-start-lb"]'
spec:
  replicas: 3
  selector:
    matchLabels:
      applicationName: oauth_start
  template:
    metadata:
      labels:
        applicationName: oauth_start
    spec:
      containers:
        - name: oauth_start
          image: 201599078153.dkr.ecr.us-east-1.amazonaws.com/oauth_start
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080

# Trigger !!
